remote_theme: "mmistakes/minimal-mistakes@4.28.1"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "contrast"

locale: "en-US"

title: "Jeremy Lenoir - Software Engineer"
name: "name"
description: "My personal website"
url: "https://Jeremy-afk.github.io"

markdown: kramdown

author:
  name: "Name"